[*] Running ...
[*] Dataset loaded: /Users/yhr/Desktop/llm-workspace/llm-as-meta-optimizer/problems/tsp_constructive/dataset/val50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "/Users/yhr/anaconda3/lib/python3.11/site-packages/networkx/convert.py", line 144, in to_networkx_graph
    return nx.from_numpy_array(data, create_using=create_using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yhr/anaconda3/lib/python3.11/site-packages/networkx/convert_matrix.py", line 1615, in from_numpy_array
    raise nx.NetworkXError(f"Adjacency matrix not square: nx,ny={A.shape}")
networkx.exception.NetworkXError: Adjacency matrix not square: nx,ny=(49, 50)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yhr/Desktop/llm-workspace/llm-as-meta-optimizer/problems/tsp_constructive/eval.py", line 66, in <module>
    obj = eval_heuristic(node_positions[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yhr/Desktop/llm-workspace/llm-as-meta-optimizer/problems/tsp_constructive/eval.py", line 37, in eval_heuristic
    next_node = select_next_node(
                ^^^^^^^^^^^^^^^^^
  File "/Users/yhr/Desktop/llm-workspace/llm-as-meta-optimizer/problems/tsp_constructive/gpt.py", line 19, in select_next_node
    num_unvisited_neighbors = len(unvisited_nodes.intersection(set(np.nonzero(distance_matrix[node])[0])))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yhr/anaconda3/lib/python3.11/site-packages/networkx/classes/graph.py", line 338, in __init__
    convert.to_networkx_graph(incoming_graph_data, create_using=self)
  File "/Users/yhr/anaconda3/lib/python3.11/site-packages/networkx/convert.py", line 146, in to_networkx_graph
    raise nx.NetworkXError(
networkx.exception.NetworkXError: Failed to interpret array as an adjacency matrix.
